docker-compose up   
Recreating mongo ... done
Recreating app   ... done
Attaching to mongo, app
mongo    | 2019-04-16T23:54:39.763+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=5f38d8ea3024
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] db version v4.0.6
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] git version: caa42a1f75a56c7643d0b68d3880444375ec42e3
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] modules: none
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] build environment:
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo    | 2019-04-16T23:54:39.768+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo    | 2019-04-16T23:54:39.772+0000 W STORAGE  [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
mongo    | 2019-04-16T23:54:39.777+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo    | 2019-04-16T23:54:39.781+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
mongo    | 2019-04-16T23:54:39.782+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
app      | 
app      | > reddit-clone@1.0.0 start /usr/src/app
app      | > node server.js
app      | 
app      | Port is listening on 3000
app      | MongoDB connection Error: { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
app      |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:564:11)
app      |     at Pool.emit (events.js:193:13)
app      |     at Connection.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:317:12)
app      |     at Object.onceWrapper (events.js:281:20)
app      |     at Connection.emit (events.js:193:13)
app      |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:246:50)
app      |     at Object.onceWrapper (events.js:281:20)
app      |     at Socket.emit (events.js:193:13)
app      |     at emitErrorNT (internal/streams/destroy.js:91:8)
app      |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
app      |     at processTicksAndRejections (internal/process/task_queues.js:81:17)
app      |   name: 'MongoNetworkError',
app      |   errorLabels: [ 'TransientTransactionError' ],
app      |   [Symbol(mongoErrorContextSymbol)]: {} }
mongo    | 2019-04-16T23:54:53.330+0000 I STORAGE  [initandlisten] WiredTiger message [1555458893:330374][1:0x7f00d1273a40], txn-recover: Main recovery loop: starting at 14/2944 to 15/256
mongo    | 2019-04-16T23:54:53.363+0000 I STORAGE  [initandlisten] WiredTiger message [1555458893:363338][1:0x7f00d1273a40], txn-recover: Recovering log 14 through 15
mongo    | 2019-04-16T23:54:54.042+0000 I STORAGE  [initandlisten] WiredTiger message [1555458894:42720][1:0x7f00d1273a40], file:sizeStorer.wt, txn-recover: Recovering log 15 through 15
mongo    | 2019-04-16T23:54:54.110+0000 I STORAGE  [initandlisten] WiredTiger message [1555458894:110816][1:0x7f00d1273a40], file:sizeStorer.wt, txn-recover: Set global recovery timestamp: 0
mongo    | 2019-04-16T23:54:54.167+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo    | 2019-04-16T23:54:54.277+0000 I CONTROL  [initandlisten] 
mongo    | 2019-04-16T23:54:54.277+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo    | 2019-04-16T23:54:54.278+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo    | 2019-04-16T23:54:54.278+0000 I CONTROL  [initandlisten] 
mongo    | 2019-04-16T23:54:54.365+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo    | 2019-04-16T23:54:54.372+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongo    | 2019-04-16T23:54:55.016+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK